import Head from 'next/head';
import Hero from '../components/Hero';
import ContactForm from '../components/ContactForm';
import Slider from '../components/Slider';
import { sliderPicsData } from '../data/sliderPicsData';

export default function Home() {
  return (
    <>
      <Head>
        <title>Ian&apos;s Coding Projects</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero
        heading="A collection of Ian's coding projects"
        about='"Intellectual growth should commence at birth and cease only at death." - Albert Einstein'
        projects='Projects'
      />
      <Slider slides={sliderPicsData} />
      <ContactForm />
    </>
  );
}
